### ISSUE TITLE
Hubs.Get node does not return anything

### ISSUE THREAD

**Issue by nicobrownHL** [EverseDevelopment/DynaForge#1]
Thanks for the packages but I've got an issue, I downloaded from the package manager in dynamo.

The Auth node returns its token but this doesn't work with the hubs.get which just returns empty. I also checked with our in-house Auth token node but still nothing.

![image](https://user-images.githubusercontent.com/86722075/137497580-9ab1ee4b-61ab-4467-aec9-5a4606581914.png)

I've also had an issue with the StorageLocation.Create node

![image](https://user-images.githubusercontent.com/86722075/137498946-2b300d48-1471-49ed-a19a-ebf578239160.png)

I'm trying to access and eventually upload a Revit file to BIM 360, will these nodes be able to do this?

**Comment by vnoves** [comment]
HI @nicobrownHL , thanks for your interest in DynaForge.


1. Regarding the Hubs.Get node, did you already created a Forge app and then added the custom integration to BIM360?

![image](https://user-images.githubusercontent.com/13223522/137816475-15957790-2362-4569-9be8-de188e939f9f.png)

2. Please confirm the above so then we can check the StorageLocation.Create node

3. Yes, it's the idea that you will be able to upload files to BIM360. We will be soon releasing a new version of the nodes with more functionality too. Any suggestions are always accepted :)

**Comment by nicobrownHL** [comment]
Hi Valentin,

I've edited this comment twice now but I've generated an app with just a local callback location as described above and its working but I'm still having an issue trying to upload a file.
Are these nodes in the correct order and are the inputs correct?
![image](https://user-images.githubusercontent.com/86722075/137893639-6a98d274-5020-4757-a5c8-3dee408a3073.png)

**Comment by vnoves** [comment]
Hi @nicobrownHL 

I think you are not using the nodes in the correct order.

1. Get your token with Authenticate.Auth Node
2. Get you desired hub id with Hubs.Get Node. Always select the middle option(hub_id)
3. Get a project with the Projects.Get Node

![image](https://user-images.githubusercontent.com/13223522/137908222-249145de-7a54-42c9-8d76-736e349a2035.png)

4. Get a folder ID, you can use the TopFolderContent.Get
5. Create an storage for your file with the StorageLocation.Create

![image](https://user-images.githubusercontent.com/13223522/137908517-220cfb01-fdbf-40ce-8c52-5e183547bcb6.png)

6. Upload a file from your computer using the FileUpload.Run
7. Finally Create the file in BIM360 with FileCreate.Run

![image](https://user-images.githubusercontent.com/13223522/137908762-1b08a568-63b1-4138-8f92-da2ad8ebd2e0.png)

Let me know if that works

**Comment by nicobrownHL** [comment]
Ok I built it with the nodes as above and its fine so apologies for wasting your time. 
I was trying to skip some of the inputs by cutting and pasting the web address into the graph and then processing them as strings to get the desired project and folder ID to simplify the graph a bit, but even though they match the ID output of the nodes they don't seem to work. 
I'll create some DS UI forms for the project and folder selections for those who aren't so dynamo savvy.
Thanks for making these packages, super useful and something we've been trying to look at for ages.

**Comment by vnoves** [comment]
I'm glad it is working now. Thanks for the feedback, I will create a wiki for the project with examples like this one, so it is easier to understand how to do certain actions.

Regarding the DS UI Forms, that is a great idea, I look forward to the PR! :)
